version: "3"
services:
  backend:
    image: ajay2929/fullstack-deploy-docker-on-ec2:01
    container_name: fullstack-backend
    ports:
      - "5000:5000"

  frontend:
    image: ajay2929/fullstack-deploy-docker-on-ec2:02
    container_name: fullstack-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: fullstack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend