version: "3.9"

services:
  backend:
    build: ./backend
    image: ajay2929/fullstack-deploy-docker-on-ec2-v1:02
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    image: ajay2929/fullstack-deploy-docker-on-ec2-v1:01
    container_name: frontend-app
    ports:
      - "80:80"